export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const REMOVE_PRODUCT_FROM_CART = "REMOVE_PRODUCT_FROM_CART";
export const GET_PRODUCT_DATA_ARRAY = "GET_PRODUCT_DATA_ARRAY";
export const SELECTED_CATEGORY = "SELECTED_CATEGORY";
export const SEARCH_TERM = "SEARCH_TERM";
export const RECENTLY_VIEWED = "RECENTLY_VIEWED";
export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";
export const MODAL = "MODAL";

export const GET_LIKED_PRODUCTS = "GET_LIKED_PRODUCTS";
export const GET_LIKED_PRODUCTS_LOADED = "GET_LIKED_PRODUCTS_LOADED";
export const GET_LIKED_PRODUCTS_ERROR = "GET_LIKED_PRODUCTS_ERROR";

export const UPDATE_LIKED_PRODUCTS = "UPDATE_LIKED_PRODUCTS";
export const UPDATE_LIKED_PRODUCT_ERROR = "UPDATE_LIKED_PRODUCT_ERROR";

export const UPDATE_LIKED_PRODUCTS_LOADED = "UPDATE_LIKED_PRODUCTS_LOADED";
export const UPDATE_LIKED_PRODUCTS_LOADED_ERROR =
  "UPDATE_LIKED_PRODUCTS_LOADED_ERROR";

export const DELETE_LIKED_PRODUCT = "DELETE_LIKED_PRODUCT";
export const DELETE_LIKED_PRODUCT_LOADED = "DELETE_LIKED_PRODUCT_LOADED";
export const DELETE_LIKED_PRODUCT_ERROR = "DELETE_LIKED_PRODUCT_ERROR";

export const GET_USER = "GET_USER";
export const GET_USER_LOADED = "GET_USER_LOADED";
export const GET_USER_ERROR = "GET_USER_ERROR";

export const CREATE_USER = "CREATE_USER";
export const CREATE_USER_LOADED = "CREATE_USER_LOADED";
export const CREATE_USER_ERROR = "CREATE_USER_ERROR";

export const DELETE_USER = "DELETE_USER";
export const DELETE_USER_LOADED = "DELETE_USER_LOADED";
export const DELETE_USER_ERROR = "DELETE_USER_ERROR";

export const LOG_OUT = "LOG_OUT";

export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_LOADED = "UPDATE_USER_LOADED";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const CLEAR_ERROR = "CLEAR_ERROR";
