const productDataArray = [
  {
    id: "25fc09f8-f662-4043-8b8c-389e466dcd3c",
    name: "FEATURED",
    price: 55,
    category: "car",
    inStock: true,
    location: "Stara Zagora",
    rating: 5,
    featured: true,
  },
  {
    id: "8db5a6b2-5d11-4477-a922-3a2f2e04731a",
    name: "NOT FEATURED",
    price: 75,
    category: "electronics",
    inStock: false,
    location: "Stara Zagora",
    rating: 2,
    featured: false,
  },
  {
    id: "66f44b43-b068-41a9-898f-e1212930ce26",
    name: "eu aute",
    price: 762,
    category: "car",
    inStock: false,
    location: "Sofia",
    rating: 5,
    featured: true,
    img: "/images/trfProduct.jpg",
  },
  {
    id: "845c341b-adb4-4666-8963-02cbf7d0f3e7",
    name: "aliqua est",
    price: 899,
    category: "food",
    inStock: false,
    location: "Sofia",
    rating: 1,
    featured: true,
    img: "/images/trfProduct.jpg",
  },
  {
    id: "d37b6fbd-c97e-429e-9347-7996d231bbff",
    name: "sint reprehenderit",
    price: 159,
    category: "clothes",
    inStock: true,
    location: "Sofia",
    rating: 4,
    featured: true,
    img: "/images/trfProduct.jpg",
  },
  {
    id: "2c850fe2-67fb-4f0b-b9af-b7c22eab5493",
    name: "labore ipsum",
    price: 275,
    category: "car",
    inStock: false,
    location: "Plovdiv",
    rating: 1,
    featured: true,
    img: "/images/trfProduct.jpg",
  },
  {
    id: "acafc0af-e096-4615-9a92-2ee5f5cf8770",
    name: "ex sit",
    price: 693,
    category: "car",
    inStock: false,
    location: "Plovdiv",
    rating: 5,
    featured: true,
    img: "/images/trfProduct.jpg",
  },
  {
    id: "74eec488-d13e-4b7e-bb8b-697392ce639d",
    name: "qui excepteur",
    price: 807,
    category: "clothes",
    inStock: true,
    location: "Plovdiv",
    rating: 3,
    featured: true,
    img: "/images/trfProduct.jpg",
  },
  {
    id: "fde74ec8-e9e5-489a-9cdf-bd9f9cb73738",
    name: "est exercitation",
    price: 701,
    category: "clothes",
    inStock: false,
    location: "Stara Zagora",
    rating: 5,
    featured: true,
    img: "/images/trfProduct.jpg",
  },
  {
    id: "e33950b0-4149-4345-bf71-a9fd4f0327cd",
    name: "officia tempor",
    price: 449,
    category: "food",
    inStock: false,
    location: "Stara Zagora",
    rating: 3,
    featured: true,
    img: "/images/trfProduct.jpg",
  },
  {
    id: "4b3d8ef3-6887-4226-bb5e-1fac61ee13dc",
    name: "Lorem eiusmod",
    price: 993,
    category: "garden",
    inStock: false,
    location: "Plovdiv",
    rating: 5,
    img: "/images/trfProduct.jpg",
    featured: false,
  },
  {
    id: "ec7a1d70-1ab9-49dd-a936-abc07d58d9b9",
    name: "amet aute",
    price: 62,
    category: "food",
    inStock: true,
    location: "Stara Zagora",
    rating: 1,
    featured: true,
    img: "/images/trfProduct.jpg",
  },
  {
    id: "1fff66d2-9253-44e9-a64a-dff637002af9",
    name: "reprehenderit incididunt",
    price: 716,
    category: "clothes",
    inStock: true,
    location: "Sofia",
    rating: 4,
    img: "/images/trfProduct.jpg",
    featured: false,
  },
  {
    id: "7f473a59-ec35-4b55-8d8e-14d717db6033",
    name: "consequat excepteur",
    price: 330,
    category: "electronics",
    inStock: true,
    location: "Plovdiv",
    rating: 3,
    img: "/images/trfProduct.jpg",
    featured: false,
  },
  {
    id: "5dc33b93-1c2d-4e83-af59-b2db3c6f4bec",
    name: "consectetur adipisicing",
    price: 247,
    category: "food",
    inStock: false,
    location: "Sofia",
    rating: 1,
    img: "/images/trfProduct.jpg",
    featured: false,
  },
  {
    id: "715b7c91-69c6-4a9c-9e87-9aae9e6cbc04",
    name: "nulla velit",
    price: 224,
    category: "clothes",
    inStock: true,
    location: "Sofia",
    rating: 5,
    img: "/images/trfProduct.jpg",
    featured: false,
  },
  {
    id: "ac99a201-0182-4fb0-ad12-08434d8b5929",
    name: "laborum irure",
    price: 180,
    category: "electronics",
    inStock: true,
    location: "Stara Zagora",
    rating: 3,
    img: "/images/trfProduct.jpg",
    featured: false,
  },
  {
    id: "6255988c-3fc2-4f7f-a391-c8415ab0ef50",
    name: "officia est",
    price: 763,
    category: "clothes",
    inStock: true,
    location: "Stara Zagora",
    rating: 1,
    img: "/images/trfProduct.jpg",
    featured: false,
  },
  {
    id: "50b035ba-0418-4217-882b-a00438832691",
    name: "reprehenderit culpa",
    price: 173,
    category: "clothes",
    inStock: false,
    location: "Sofia",
    rating: 3,
    img: "/images/trfProduct.jpg",
    featured: false,
  },
  {
    id: "15a172bd-25ae-49eb-af38-999da04c85ed",
    name: "excepteur dolore",
    price: 540,
    category: "electronics",
    inStock: false,
    location: "Stara Zagora",
    rating: 1,
    img: "/images/trfProduct.jpg",
    featured: false,
  },
  {
    id: "4aa1bb6c-8b9c-4ae0-aeb9-170091b335c1",
    name: "cillum sit",
    price: 305,
    category: "electronics",
    inStock: true,
    location: "Stara Zagora",
    rating: 1,
    img: "/images/trfProduct.jpg",
    featured: false,
  },
  {
    id: "351e9c2d-97e7-492c-a5c8-a890dc11a780",
    name: "velit irure",
    price: 809,
    category: "food",
    inStock: true,
    location: "Plovdiv",
    rating: 4,
    img: "/images/trfProduct.jpg",
    featured: false,
  },
  {
    id: "aa56f1ee-7d6d-4e0d-82df-5aff55878525",
    name: "ipsum irure",
    price: 158,
    category: "clothes",
    inStock: true,
    location: "Sofia",
    rating: 2,
    img: "/images/trfProduct.jpg",
    featured: false,
  },
  {
    id: "7a782910-b9d7-4e9f-86f3-6d417cab1614",
    name: "ullamco dolor",
    price: 486,
    category: "car",
    inStock: true,
    location: "Sofia",
    rating: 5,
    img: "/images/trfProduct.jpg",
    featured: false,
  },
  {
    id: "f96322e8-0bbf-49ed-ac27-5408459ab7df",
    name: "consectetur reprehenderit",
    price: 203,
    category: "car",
    inStock: false,
    location: "Plovdiv",
    rating: 2,
    img: "/images/trfProduct.jpg",
    featured: false,
  },
  {
    id: "89447da0-5fb2-4e53-a01d-56e1bdfbefe6",
    name: "laboris magna",
    price: 152,
    category: "garden",
    inStock: false,
    location: "Sofia",
    rating: 2,
    img: "/images/trfProduct.jpg",
    featured: false,
  },
  {
    id: "d614ac64-734e-4ad7-94c3-b0d6c4d05f8c",
    name: "ullamco nostrud",
    price: 237,
    category: "food",
    inStock: true,
    location: "Sofia",
    rating: 2,
    img: "/images/trfProduct.jpg",
    featured: false,
  },
  {
    id: "95c6ad9f-75f4-4237-b3c6-257c125d6a91",
    name: "voluptate in",
    price: 48,
    category: "electronics",
    inStock: true,
    location: "Sofia",
    rating: 3,
    img: "/images/trfProduct.jpg",
    featured: false,
  },
  {
    id: "83efd1be-3968-45d5-b487-b636c5ae7122",
    name: "aliquip Lorem",
    price: 809,
    category: "clothes",
    inStock: true,
    location: "Stara Zagora",
    rating: 5,
    img: "/images/trfProduct.jpg",
    featured: false,
  },
  {
    id: "9fdd04c9-0675-4c2f-8f92-9b004dee412c",
    name: "amet laborum",
    price: 10,
    category: "electronics",
    inStock: false,
    location: "Plovdiv",
    rating: 2,
    img: "/images/trfProduct.jpg",
    featured: false,
  },
  {
    id: "5c62e84a-caf4-4c23-862e-b2f64b5e951e",
    name: "in labore",
    price: 815,
    category: "car",
    inStock: true,
    location: "Sofia",
    rating: 3,
    img: "/images/trfProduct.jpg",
    featured: false,
  },
  {
    id: "ffb78006-ea58-4701-a467-39c383ecc3f8",
    name: "nulla exercitation",
    price: 632,
    category: "garden",
    inStock: false,
    location: "Plovdiv",
    rating: 5,
    img: "/images/trfProduct.jpg",
    featured: false,
  },
  {
    id: "fd17038c-a8bd-474a-80c1-490315b63385",
    name: "duis officia",
    price: 518,
    category: "car",
    inStock: false,
    location: "Plovdiv",
    rating: 5,
    img: "/images/trfProduct.jpg",
    featured: false,
  },
  {
    id: "6f8b29c2-7f3a-4aa4-a0a6-88309116f476",
    name: "labore aute",
    price: 844,
    category: "food",
    inStock: true,
    location: "Plovdiv",
    rating: 3,
    img: "/images/trfProduct.jpg",
    featured: false,
  },
  {
    id: "f05f7853-df5a-4496-b76d-00d48043b7e2",
    name: "laboris deserunt",
    price: 658,
    category: "electronics",
    inStock: true,
    location: "Stara Zagora",
    rating: 4,
    img: "/images/trfProduct.jpg",
    featured: false,
  },
  {
    id: "1d55a3d5-8e81-4eaf-9f98-c3e54d94bdc9",
    name: "sit cillum",
    price: 989,
    category: "garden",
    inStock: false,
    location: "Stara Zagora",
    rating: 3,
    img: "/images/trfProduct.jpg",
    featured: false,
  },
  {
    id: "2a03d1cf-5f68-42c5-8de8-423ebd010b3c",
    name: "dolor officia",
    price: 982,
    category: "food",
    inStock: false,
    location: "Stara Zagora",
    rating: 3,
    img: "/images/trfProduct.jpg",
    featured: false,
  },
  {
    id: "8b36beb5-06cb-458b-a679-199fd2d79bba",
    name: "eu aliquip",
    price: 981,
    category: "electronics",
    inStock: false,
    location: "Plovdiv",
    rating: 2,
    img: "/images/trfProduct.jpg",
    featured: false,
  },
  {
    id: "91f374d9-a6a3-44d8-9d82-c691aa2c1269",
    name: "non nisi",
    price: 102,
    category: "electronics",
    inStock: true,
    location: "Sofia",
    rating: 5,
    img: "/images/trfProduct.jpg",
    featured: false,
  },
  {
    id: "cd1dde6c-e291-476e-b8d5-70c76f003974",
    name: "dolor consectetur",
    price: 789,
    category: "car",
    inStock: true,
    location: "Stara Zagora",
    rating: 5,
    img: "/images/trfProduct.jpg",
    featured: false,
  },
  {
    id: "2a26004e-8ff6-4ec2-8f00-9060c955bc83",
    name: "adipisicing aliquip",
    price: 906,
    category: "garden",
    inStock: true,
    location: "Sofia",
    rating: 4,
    img: "/images/trfProduct.jpg",
    featured: false,
  },
  {
    id: "cafe8052-7561-4e7d-81ad-ac662ee57cd1",
    name: "id quis",
    price: 835,
    category: "car",
    inStock: false,
    location: "Stara Zagora",
    rating: 4,
    img: "/images/trfProduct.jpg",
    featured: false,
  },
  {
    id: "6d799cd2-30c5-4fd6-81a2-3781c3805c4f",
    name: "et magna",
    price: 30,
    category: "electronics",
    inStock: false,
    location: "Stara Zagora",
    rating: 4,
    img: "/images/trfProduct.jpg",
    featured: false,
  },
  {
    id: "cf6a82b6-4c30-4e44-a86b-85d58bdbe966",
    name: "deserunt ipsum",
    price: 230,
    category: "food",
    inStock: true,
    location: "Stara Zagora",
    rating: 1,
    img: "/images/trfProduct.jpg",
    featured: false,
  },
  {
    id: "5e546909-2cc9-45f8-ac72-a01ec0f13c4f",
    name: "voluptate nisi",
    price: 30,
    category: "clothes",
    inStock: false,
    location: "Plovdiv",
    rating: 1,
    img: "/images/trfProduct.jpg",
    featured: false,
  },
  {
    id: "b7ca1d6f-1a4f-4c68-9bc7-b1ab2d2a7018",
    name: "laborum aliqua",
    price: 205,
    category: "clothes",
    inStock: true,
    location: "Sofia",
    rating: 2,
    img: "/images/trfProduct.jpg",
    featured: false,
  },
  {
    id: "88fe59d8-5827-4ef2-8cf3-0c757934c4ba",
    name: "eu officia",
    price: 553,
    category: "clothes",
    inStock: false,
    location: "Plovdiv",
    rating: 5,
    img: "/images/trfProduct.jpg",
    featured: false,
  },
  {
    id: "ed6d440b-1cce-4d12-885d-9877778591fa",
    name: "nisi labore",
    price: 531,
    category: "electronics",
    inStock: true,
    location: "Sofia",
    rating: 5,
    img: "/images/trfProduct.jpg",
    featured: false,
  },
  {
    id: "14f81861-2f3b-41df-a9af-b1f0135c83c6",
    name: "veniam laborum",
    price: 808,
    category: "car",
    inStock: true,
    location: "Stara Zagora",
    rating: 3,
    img: "/images/trfProduct.jpg",
    featured: false,
  },
  {
    id: "176667c2-0c15-4527-82bd-a704e255804f",
    name: "Lorem non",
    price: 358,
    category: "clothes",
    inStock: true,
    location: "Plovdiv",
    rating: 2,
    img: "/images/trfProduct.jpg",
    featured: false,
  },
  {
    id: "7281eefd-b82e-4bb8-8921-604f4a5bc735",
    name: "fugiat proident",
    price: 762,
    category: "clothes",
    inStock: true,
    location: "Plovdiv",
    rating: 2,
    img: "/images/trfProduct.jpg",
    featured: false,
  },
];

export default productDataArray;
