const registeredUsersArray = [
  {
    username: "yoman4o",
    password: "123",
    name: "Simeon Radev",
    img: "/images/userImg.jpg",
    age: 28,
    description: "A long time ago in a galaxy far, far away....",
    favoriteProducts: [
      {
        id: "25fc09f8-f662-4043-8b8c-389e466dcd3c",
        name: "FEATURED",
        price: 55,
        category: "car",
        inStock: true,
        location: "Stara Zagora",
        rating: 5,
        featured: true,
      },
      {
        id: "8db5a6b2-5d11-4477-a922-3a2f2e04731a",
        name: "NOT FEATURED",
        price: 75,
        category: "electronics",
        inStock: false,
        location: "Stara Zagora",
        rating: 2,
        featured: false,
      },
      {
        id: "66f44b43-b068-41a9-898f-e1212930ce26",
        name: "eu aute",
        price: 762,
        category: "car",
        inStock: false,
        location: "Sofia",
        rating: 5,
        featured: true,
        img: "/images/trfProduct.jpg",
      },
    ],
  },
  {
    username: "ivan4o",
    password: "12345",
    name: "Ivon4o Be",
    img: "/images/userImg.jpg",
    age: 12,
    description: "A long time ago in a galaxy far, far away....",
    favoriteProducts: [
      {
        id: "845c341b-adb4-4666-8963-02cbf7d0f3e7",
        name: "aliqua est",
        price: 899,
        category: "food",
        inStock: false,
        location: "Sofia",
        rating: 1,
        featured: true,
        img: "/images/trfProduct.jpg",
      },
      {
        id: "d37b6fbd-c97e-429e-9347-7996d231bbff",
        name: "sint reprehenderit",
        price: 159,
        category: "clothes",
        inStock: true,
        location: "Sofia",
        rating: 4,
        featured: true,
        img: "/images/trfProduct.jpg",
      },
      {
        id: "2c850fe2-67fb-4f0b-b9af-b7c22eab5493",
        name: "labore ipsum",
        price: 275,
        category: "car",
        inStock: false,
        location: "Plovdiv",
        rating: 1,
        featured: true,
        img: "/images/trfProduct.jpg",
      },
    ],
  },
  {
    username: "stoqn4o",
    password: "12345",
    name: "Stoqn4o Be",
    img: "/images/userImg.jpg",
    age: 65,
    description: "A long time ago in a galaxy far, far away....",
    favoriteProducts: [
      {
        id: "acafc0af-e096-4615-9a92-2ee5f5cf8770",
        name: "ex sit",
        price: 693,
        category: "car",
        inStock: false,
        location: "Plovdiv",
        rating: 5,
        featured: true,
        img: "/images/trfProduct.jpg",
      },
      {
        id: "74eec488-d13e-4b7e-bb8b-697392ce639d",
        name: "qui excepteur",
        price: 807,
        category: "clothes",
        inStock: true,
        location: "Plovdiv",
        rating: 3,
        featured: true,
        img: "/images/trfProduct.jpg",
      },
      {
        id: "fde74ec8-e9e5-489a-9cdf-bd9f9cb73738",
        name: "est exercitation",
        price: 701,
        category: "clothes",
        inStock: false,
        location: "Stara Zagora",
        rating: 5,
        featured: true,
        img: "/images/trfProduct.jpg",
      },
    ],
  },
];

export default registeredUsersArray;
